upstreams:
  spack-software:
    install_tree: /nopt/nrel/ecom/hpacf/software/2020-07/spack/opt/spack
  spack-utilities:
    install_tree: /nopt/nrel/ecom/hpacf/utilities/2020-07/spack/opt/spack
  spack-compilers:
    install_tree: /nopt/nrel/ecom/hpacf/compilers/2020-07/spack/opt/spack
