modules:
  enable:
    - tcl
  tcl:
    projections:
      all: '{compiler.name}-{compiler.version}/{name}/{version}/{hash:4}'
    hash_length: 0
    all:
      conflict:
        - '{name}'
      environment:
        set:
          '{name}_ROOT_DIR': '{prefix}'
    mpich:
      environment:
        set:
          'UCX_NET_DEVICES': 'mlx5_0:1'
    #^python:
    #  autoload: 'direct'
    #blacklist: ['cmake', 'llvm']
