config:
  install_tree: $spack/opt/spack
  module_roots:
    tcl:    $spack/share/spack/modules
    lmod:   $spack/share/spack/lmod
    dotkit: $spack/share/spack/dotkit
  build_stage:
    - $spack/var/spack/stage
  # Use a common source archive for each user across all Spack installations
  # to avoid downloading more than once. Probably would be better to have a 
  # site-wide Spack source cache for all users though.
  source_cache: ~/.spack/cached_archives
  misc_cache: ~/.spack/cache
  verify_ssl: false
  checksum: true
  dirty: false
